#version: "3.8"
#
#services:
#  app:
#    build: .
#    command: sh -c "python3 -m uvicorn app.app:app --port=8000 --host=0.0.0.0"
#    ports:
#      - 8000:8000
#    depends_on:
#      - db
#    volumes:
#      - .:/app
#  db:
#    image: postgres
#    restart: always
#    ports:
#      - "5051:5432"
#    environment:
#      - POSTGRES_USER=${DB_USERNAME}
#      - POSTGRES_PASSWORD=${DB_PASSWORD}
#      - POSTGRES_DB=${DB_NAME}
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
#      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
#    ports:
#      - "80:80"
#    depends_on:
#      - db