FROM python:3.8.10

WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt

EXPOSE 8080

#ENV DB_USERNAME=${DB_USERNAME}
#ENV DB_PASSWORD=${DB_PASSWORD}
#ENV DB_NAME=${DB_NAME}
#ENV HOST_SERVER=${HOST_SERVER}
#ENV DB_SERVER_PORT=${DB_SERVER_PORT}
#ENV SSL_MODE=${SSL_MODE}
#ENV PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
#ENV PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
#ENV SECRET_KEY=${SECRET_KEY}
#ENV ALGORITHM=${ALGORITHM}

CMD ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "8080:8080"]