name: test-and-deploy

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: python -m pytest ./tests
  docker:
    needs: test
    runs-on: ubuntu-latest
    env:
      DB_USERNAME=${{ vars.DB_USERNAME}}
      DB_PASSWORD=${{ vars.DB_PASSWORD}}
      DB_NAME=${{ vars.DB_NAME}}
      HOST_SERVER=${{ vars.HOST_SERVER}}
      DB_SERVER_PORT=${{ vars.DB_SERVER_PORT}}
      SSL_MODE=${{ vars.SSL_MODE}}
      PGADMIN_DEFAULT_EMAIL=${{ vars.PGADMIN_DEFAULT_EMAIL}}
      PGADMIN_DEFAULT_PASSWORD=${{ vars.PGADMIN_DEFAULT_PASSWORD}}
      SECRET_KEY=${{ vars.SECRET_KEY}}
      ALGORITHM=${{ vars.ALGORITHM}}
      TEST_USER=${{ vars.TEST_USER}}
      TEST_PASSWORD=${{ vars.TEST_PASSWORD}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: jolual2747/ecommerce:latest
          